export const plinkoSettings = {
  preloadImagesNonBlocking: {
    santaLoading: "/plinko/lottie/SantaLoading.lottie",
    giftTagGold: "/plinko/other/GiftTagGold.webp",
    giftTagGoldFilled: "/plinko/other/GiftTagGoldFilled.webp",
    bottomScene: "/plinko/other/BottomScene.webp",
    snowfallBackground: "/plinko/other/Snowfall_Background.webp",
    plinkoTitleImage: "/plinko/other/PlinkoHeader_Alone.webp",
  },
  preloadImagesBlocking: {
    hand: "/plinko/textures/hand.png",
    icyMtnForLeftSide: "/plinko/textures/icy-mtn-for-left-side.png",
    icyMtnForRightSide: "/plinko/textures/icy-mtn-for-right-side.png",
    goldOrnamentPlinko: "/plinko/other/GoldOrnamentPlinko.webp",
    redOrnamentPlinko: "/plinko/other/RedOrnamentPlinko.webp",
    pocketRedSac: "/plinko/textures/Red_Giftbag.png",
    candyCaneDivider: "/plinko/textures/CandyCaneDivider.png",
  },
  pocketKeys: [
    "pocket_middle_left_3",
    "pocket_middle_left_2",
    "pocket_middle_left_1",
    "pocket_middle",
    "pocket_middle_right_1",
    "pocket_middle_right_2",
    "pocket_middle_right_3",
  ],
  plinkoBallKeys: [
    "plinko_ball_1",
    "plinko_ball_2",
    "plinko_ball_3",
    "plinko_ball_4",
    "plinko_ball_5",
    "plinko_ball_6",
    "plinko_ball_7",
    "plinko_ball_8",
    "plinko_ball_9",
    "plinko_ball_10",
  ],
  // pocketWidth: width / 7, // this number should be the the length of pocketKeys
  pocketHeight: 50,
  pocketDividerHeight: 100,
  pegScore: 30,
} as const;
