# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraform-state-sensitive"
    encrypt = true
    key     = "theadpharm.com/terraform.tfstate"
    profile = "pharmer"
    region  = "ca-central-1"
  }
}
