FROM mcr.microsoft.com/devcontainers/base:jammy

# use user "vscode"
USER vscode

# install Bun
RUN curl -fsSL https://bun.sh/install | bash

# install pnpm
# RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
