# Generated by Django 5.1 on 2024-12-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField()),
                (
                    "board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="plinko.board"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("one", "One"),
                            ("two_a", "Two A"),
                            ("two_b", "Two B"),
                            ("three_a", "Three A"),
                            ("three_b", "Three B"),
                            ("four_a", "Four A"),
                            ("four_b", "Four B"),
                            ("five_a", "Five A"),
                            ("five_b", "Five B"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (0, "Zero"),
                            (100, "Hundred"),
                            (500, "Five Hundred"),
                            (1000, "One Thousand"),
                            (10000, "Ten Thousand"),
                        ]
                    ),
                ),
                (
                    "power_up",
                    models.CharField(
                        choices=[("none", "None"), ("double", "Double")],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plinko.board"
                    ),
                ),
            ],
            options={
                "ordering": ["board", "name"],
                "unique_together": {("name", "board")},
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("round1", "Round 1"),
                            ("round2", "Round 2"),
                            ("round3", "Round 3"),
                            ("round4", "Round 4"),
                            ("round5", "Round 5"),
                            ("round6", "Round 6"),
                            ("round7", "Round 7"),
                            ("round8", "Round 8"),
                            ("round9", "Round 9"),
                            ("round10", "Round 10"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plinko.game"
                    ),
                ),
            ],
            options={
                "ordering": ["game", "name"],
                "unique_together": {("name", "game")},
            },
        ),
    ]
