# Generated by Django 5.1 on 2024-12-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plinko", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pocket",
            options={"ordering": ["board", "key"]},
        ),
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["game", "key"]},
        ),
        migrations.RenameField(
            model_name="pocket",
            old_name="name",
            new_name="key",
        ),
        migrations.RenameField(
            model_name="round",
            old_name="name",
            new_name="key",
        ),
        migrations.AlterUniqueTogether(
            name="pocket",
            unique_together={("key", "board")},
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("key", "game")},
        ),
    ]
